# This is [Compose file](https://docs.docker.com/compose/compose-file/compose-file-v3/)
# Please refer okatsn/MyJuliaSpace for more information
version: '3'

services:
  devjq:
    # service name is arbitrary
    image: my-quarto-space
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    init: true
    container_name: my-quarto-space
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ..:/home/jovyan/devspace
      - julia-depot:/home/jovyan/.julia
    command:
      - sh
      - -c
      - sleep infinity
      # - julia --project=@. -e 'using Pkg; Pkg.build("IJulia")'; sleep infinity
      # KEYNOTE:
      # - Use semi-colon to separate command
      # - build IJulia everytime is nonsense. IJulia should be built when it is installed in a certain environment. See https://pkgdocs.julialang.org/v1/managing-packages/#Building-packages
      # - `Render` error may occur due to the followings:
      #   - It is not `instantiate`d in the opening project.
      #   - It is not `precompile`d in the opening project.
      #   - These are the reasons that cause julia kernel died.
      # - `Pkg.build("IJulia")` is required only for [Updating Julia and IJulia](https://julialang.github.io/IJulia.jl/stable/manual/installation/#Updating-Julia-and-IJulia)

volumes:
  # KEYNOTE: Those defined volumes in service should be declared in the root level
  julia-depot:
