# This is [Compose file](https://docs.docker.com/compose/compose-file/compose-file-v3/)
# Please refer okatsn/MyJuliaSpace for more information
version: '3'

services:
  devjq:
    # service name is arbitrary
    image: my-quarto-space
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    init: true
    container_name: my-quarto-space
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ..:/home/jovyan/devspace
      - julia-depot:/home/jovyan/.julia
    command: sh -c "sleep infinity"

volumes:
  # KEYNOTE: Those defined volumes in service should be declared in the root level
  julia-depot:
